"""

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.


"""
"""
利用hashtable，我们先将s中字母出现的次数进行保存，随后，遍历t中的字母，此时有两种情况找到添加的字母，
第一种情况是新添加的字母没有在s中出现，直接返回这个字母
第二种情况是这个字母在s中出现了，但比s中出现多一次
"""


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        dic = dict()
        for single in s:
            dic[single] = dic.get(single, 0) + 1
        for single in t:
            if single in dic:
                dic[single] = dic[single] - 1
                if dic[single] == 0:
                    del dic[single]
            else:
                return single


"""利用之前的数组题，找出只出现一次的元素的思路，将两个字符串拼接，必然有一个字母单独出现了一次，我们可以用
异或将其找出
"""


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        return chr(reduce(operator.xor, map(ord, (s + t))))
